<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="ie lt-ie9 lt-ie8 lt-ie7 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
	<![endif]-->
	<!--[if IE 7]>
	<html class="ie lt-ie9 lt-ie8 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
		<![endif]-->
		<!--[if IE 8]>
		<html class="ie lt-ie9 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
			<![endif]-->
			<!--[if gt IE 8]>
			<html class="animations ie gt-ie8 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
				<![endif]-->
				<!--[if !IE]>
				<!-->
				<html class="animations fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
					<!-- <![endif]-->
<head>
					<title><?php print $this->translate->_("stucreatetitle");?></title>

					<!-- Meta -->
					<meta charset="utf-8">
					<meta http-equiv="X-UA-Compatible" content="IE=edge">
					<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">

					<link type="stylesheet/less" href="/less/styles.less" />

					<!-- 
	**********************************************************
	In development, use the LESS fil es and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
	<link rel="stylesheet/less" href="/less/admin/module.admin.page.signup.less" />
					-->
					<!--[if lt IE 9]>
					<link rel="stylesheet" href="/components/library/bootstrap/css/bootstrap.min.css" />
					<![endif]-->
					<link rel="stylesheet" href="/css/admin/module.admin.page.signup.min.css" />

					<!--[if lt IE 9]>
					<link rel="stylesheet" href="/components/library/bootstrap/css/bootstrap.min.css" />
					<![endif]-->
					<link rel="stylesheet" href="/css/admin/module.admin.page.form_elements.min.css" />
					<link rel="stylesheet" href="/css/admin/menu.css" />

					<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
					<!--[if lt IE 9]>
					<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
					<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
					<![endif]-->

					<script src="/components/library/jquery/jquery.min.js?v=v2.3.0"></script>
					<script src="/components/library/jquery/jquery-migrate.min.js?v=v2.3.0"></script>
					<script src="/components/library/jquery/jquery.validate.min.js"></script>
					<script src="/components/library/jquery/messages_ja.js"></script>
					
					<script src="/components/library/modernizr/modernizr.js?v=v2.3.0"></script>
					<script src="/components/plugins/less-js/less.min.js?v=v2.3.0"></script>
					<script src="/components/modules/admin/charts/flot/assets/lib/excanvas.js?v=v2.3.0"></script>
					<script src="/components/plugins/browser/ie/ie.prototype.polyfill.js?v=v2.3.0"></script>
					<script>if (/*@cc_on!@*/false && document.documentMode === 10) { document.documentElement.className+=' ie ie10'; }</script>
					<script type="text/javascript">
					$.validator.setDefaults({
				        submitHandler: function(form) { form.submit(); } 
				    });
					$.validator.addMethod("jpphone", function(value, element) { 
					      return this.optional(element) || /^\+(0){0,4}(81){1}[0-9]{9,11}$/.test(value) || /^[ ]*[\+]{0,1}(0){0,4}(1){1}[0-9]{10}[ ]*$/.test(value) || /^[ ]*[\+]{0,1}(0){0,4}(65){1}[0-9]{8}[ ]*$/.test(value); 
					      //return true; 
					  }, "電話番号入力が正しくない"); 
									    
					$().ready(function(){
						$("#studentForm").validate({
							rules:{
								phone:{
									required:true,
									jpphone:true
								},
								confirmphone:{
									required:true,
									jpphone:true
								}
							}
							});
					});
					</script>

</head>

<body class="document-body login">
					<div id="" class="container">

						<!-- NAVI  START -->

						<!-- Row -->
						<div class="row innerTB">

							<!-- Col -->
							<div class="col-md-12">

								<!-- Start Featured -->
								<div class="menu">
									<div class="row">
										<div class="col-sm-3">
											<div class="widget">
												<a href="/student/index" class="display-block bg-info innerAll text-center text-white"></i>
											</a>
											<div class="text-center innerAll">
												<a href="/student/index" class="strong  "><?php print $this->translate->_("menua");?></a>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="widget">
											<a href="/student/create" class="display-block bg-lightred innerAll text-center text-white"></i>
										</a>
										<div class="text-center innerAll">
											<a href="/student/create" class="strong  "><?php print $this->translate->_("menub");?></a>
											<div class="clearfix"></div>
										</div>
									</div>
								</div>

								<div class="col-sm-3">
									<div class="widget">
										<a href="/session/index" class="display-block bg-purple innerAll text-center text-white"></i>
									</a>
									<div class="text-center innerAll">
										<a href="/session/index" class="strong"><?php print $this->translate->_("menuc");?></a>
										<div class="clearfix"></div>
									</div>
								</div>
							</div>
							<div class="col-sm-3">
								<div class="widget">
									<a href="/session/create" class="display-block bg-gray border-bottom innerAll text-center"></i>
								</a>
								<div class="text-center innerAll">
									<a href="/session/create" class="strong  "><?php print $this->translate->_("menud");?></a>
									<div class="clearfix"></div>

								</div>
							</div>
						</div>
			</div>

		</div>
		<!-- NAVI  END -->

		<!-- Wrapper -->
		<div id="login">

			<div class="wrapper signup">
				<h1 class=>
					<?php print $this->translate->_("mjs");?>
					<br>
					<?php print $this->translate->_("stucreatehead");?> <em></em>
				</h1>
				<!-- Box -->
				<div class="widget widget-heading-simple">

					<div class="widget-head"></div>

					<div class="widget-body ">

						<!-- Form -->
						<form method="post" action="/student/create" id="studentForm">

							<!-- Row -->
							<div class="row">

								<!-- Column -->
								<div class="col-md-6 padding-none border-right">
									<div class="innerLR">
										<label class="strong"><?php print $this->translate->_("stucol2");?></label>
										<input  name="firstName" type="text" required class="input-block-level form-control" placeholder="Student First Name"/>
										<label class="strong"><?php print $this->translate->_("stucol3");?></label>
										<input name="lastName" type="text" required class="input-block-level form-control" placeholder="Student Last Name"/>
										<label class="strong"><?php print $this->translate->_("stucol8");?></label>
										<input required name="totalMonthlyMins" type="text" class="input-block-level form-control" value="<?php echo $this->tmm->d_value;?>" placeholder="<?php echo $this->tmm->d_value;?> Minutes"/>
										<label class="strong"><?php print $this->translate->_("stucol6");?></label>
										<div class="input-group date" id="datepicker1">
											<input required name="startdate" class="input-block-level form-control" type="text" placeholder="Select Start Date" />
											<span class="input-group-addon"> <i class="fa fa-th"></i>
											</span>
										</div>
										<label class="strong"><?php print $this->translate->_("stucol7");?></label>
										<div class="row">
											<select class="selectpicker col-md-12" name="membershipDur">
												<optgroup label="Duration">
													<option value="1">1 Month</option>
													<option value="3">3 Months</option>
													<option value="6">6 Months</option>
													<option value="12">12 Months</option>
												</optgroup>
											</select>
										</div>
										<br></div>
								</div>
								<!-- // Column END -->

								<!-- Column -->
								<div class="col-md-6 padding-none">
									<div class="innerLR">
										<label class="strong"><?php print $this->translate->_("stucol5");?></label>
										<input required id="email" type="email" name="email"  class="input-block-level form-control" placeholder="Student Email Address"/>
										<label class="strong"><?php print $this->translate->_("stucol12");?></label>
										<input equalTo="#email" required name="confirmemail" type="email" class="input-block-level form-control" placeholder="Confirm Student Email Address"/>
										<label class="strong"><?php print $this->translate->_("stucol4");?></label>
										<input  id="phone" name="phone" type="text" class="input-block-level form-control" placeholder="Student Telephone Number"/>
										<label class="strong"><?php print $this->translate->_("stucol13");?></label>
										<input  equalTo="#phone" name="confirmphone" type="text" class="input-block-level form-control" placeholder="Confirm Student Telephone Number"/>
										<button class="btn btn-block btn-inverse" type="submit"><?php print $this->translate->_("addstu");?></button>
									</div>
								</div>
								<!-- // Column END -->

							</div>
							<!-- // Row END -->

						</form>
						<!-- // Form END -->

					</div>
					<!-- // Box END -->
				<script type="text/javascript">
					var message = 	'<?php  echo $this->resultmessage;?>';
					if(message!=null&&message!=""){
						alert(message);
					}
				</script>
				</div>

			</div>

		</div>
		<!-- // Wrapper END -->

		<!-- Global -->
		<script>
	var basePath = '',
		commonPath = '/',
		rootPath = '../',
		DEV = false,
		componentsPath = '/components/';
	
	var primaryColor = '#e5412d',
		dangerColor = '#b55151',
		infoColor = '#5cc7dd',
		successColor = '#609450',
		warningColor = '#ab7a4b',
		inverseColor = '#45484d';
	
	var themerPrimaryColor = primaryColor;
	</script>

		<script src="/components/library/bootstrap/js/bootstrap.min.js?v=v2.3.0"></script>
		<script src="/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v2.3.0"></script>
		<script src="/components/plugins/breakpoints/breakpoints.js?v=v2.3.0"></script>
		<script src="/components/modules/admin/forms/elements/uniform/assets/lib/js/jquery.uniform.min.js?v=v2.3.0"></script>
		<script src="/components/modules/admin/forms/elements/uniform/assets/custom/js/uniform.init.js?v=v2.3.0"></script>
		<script src="/components/plugins/jquery.event.move/js/jquery.event.move.js?v=v2.3.0"></script>
		<script src="/components/plugins/jquery.event.swipe/js/jquery.event.swipe.js?v=v2.3.0"></script>
		<script src="/components/core/js/core.init.js?v=v2.3.0"></script>
		<script src="/components/modules/admin/forms/elements/bootstrap-datepicker/assets/lib/js/bootstrap-datepicker.js?v=v2.3.0"></script>
		<script src="/components/modules/admin/forms/elements/bootstrap-datepicker/assets/custom/js/bootstrap-datepicker.init.js?v=v2.3.0"></script>
</body>
	</html>