<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sticky-sidebar sidebar-hat"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sticky-sidebar sidebar-hat"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sticky-sidebar sidebar-hat"> <![endif]-->
<!--[if gt IE 8]> <html class="animations ie gt-ie8 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sticky-sidebar sidebar-hat"> <![endif]-->
<!--[if !IE]><!-->
<html
	class="animations fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sticky-sidebar sidebar-hat">
<!-- <![endif]-->
<head>
<title><?php print $this->translate->_("mjslandingpage");?></title>

<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">


<!-- 
	**********************************************************
	In development, use the LESS files and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
	<link rel="stylesheet/less" href="/less/admin/module.admin.page.courses_2.less" />
	-->

<!--[if lt IE 9]><link rel="stylesheet" href="<?php echo APP_CTX?>/components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet"
	href="<?php echo APP_CTX?>/css/admin/module.admin.page.courses_2.min.css" />
<link rel="stylesheet" href="<?php echo APP_CTX?>/css/admin/menu.css" />

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->


<script src="<?php echo APP_CTX?>/components/library/jquery/jquery.min.js?v=v2.3.0"></script>
<script src="<?php echo APP_CTX?>/components/library/jquery/jquery-migrate.min.js?v=v2.3.0"></script>
<script src="<?php echo APP_CTX?>/components/library/modernizr/modernizr.js?v=v2.3.0"></script>
<script src="<?php echo APP_CTX?>/components/plugins/less-js/less.min.js?v=v2.3.0"></script>
<script
	src="<?php echo APP_CTX?>/components/modules/admin/charts/flot/assets/lib/excanvas.js?v=v2.3.0"></script>
<script
	src="<?php echo APP_CTX?>/components/plugins/browser/ie/ie.prototype.polyfill.js?v=v2.3.0"></script>
<script>if (/*@cc_on!@*/false && document.documentMode === 10) { document.documentElement.className+=' ie ie10'; }</script>

</head>
<body class="document-body ">

	<!-- Main Container Fluid -->
	<div
		class="container-fluid menu-hidden sidebar-hidden-phone fluid menu-left">

		<!-- Sidebar menu & content wrapper -->
		<div id="wrapper">

			<!-- Sidebar Menu -->
			<!-- // Sidebar Menu END -->

			<!-- Content -->
			<div id="content" >

				<!-- Top navbar -->
				<!-- Top navbar END -->


				<div class="innerLR spacing-x2">
				<!-- 
					<a href="/login/logout">logout</a>
				 -->

					<div class="clearfix"></div>


					<div class="innerLR spacing-x2">
						<h3 class="center margin-none innerR">
							<?php print $this->translate->_("mjs");?> 
							<br><?php print $this->translate->_("adminlandingpage");?> </em>
						</h3>

						<div class="clearfix"></div>

						<!-- NAVI  START -->

						<!-- Row -->
						<div class="row innerTB">

							<!-- Col -->
							<div class="col-md-12">

								<!-- Start Featured -->
								<div class="row">
									<div class="col-sm-3">
										<div class="widget">
											<a href="<?php echo APP_CTX?>/student/index"
												class="display-block bg-info innerAll text-center text-white"></i></a>
											<div class="text-center innerAll">
												<a href="<?php echo APP_CTX?>/student/index" class="strong  ">
												<?php print $this->translate->_("menua");?></a>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="widget">
											<a href="<?php echo APP_CTX?>/student/create"
												class="display-block bg-lightred innerAll text-center text-white"></i></a>
											<div class="text-center innerAll">
												<a href="<?php echo APP_CTX?>/student/create" class="strong  "><?php print $this->translate->_("menub");?></a>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>

									<div class="col-sm-3">
										<div class="widget">
											<a href="<?php echo APP_CTX?>/session/index"
												class="display-block bg-purple innerAll text-center text-white"></i></a>
											<div class="text-center innerAll">
												<a href="<?php echo APP_CTX?>/session/index" class="strong"><?php print $this->translate->_("menuc");?></a>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									<div class="col-sm-3 ">
										<div class="widget">
											<a href="<?php echo APP_CTX?>/session/create"
												class="display-block bg-gray border-bottom innerAll text-center"></i></a>
											<div class="text-center innerAll">
												<a href="<?php echo APP_CTX?>/session/create" class="strong  "><?php print $this->translate->_("menud");?></a>
												<div class="clearfix"></div>

											</div>
										</div>
									</div>

								</div>
								<!-- NAVI  END -->
							</div>

</body>
</html>