<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="ie lt-ie9 lt-ie8 lt-ie7 fluid top-full menuh-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
	<![endif]-->
	<!--[if IE 7]>
	<html class="ie lt-ie9 lt-ie8 fluid top-full menuh-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
		<![endif]-->
		<!--[if IE 8]>
		<html class="ie lt-ie9 fluid top-full menuh-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
			<![endif]-->
			<!--[if gt IE 8]>
			<html class="animations ie gt-ie8 fluid top-full menuh-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
				<![endif]-->
				<!--[if !IE]>
				<!-->
				<html class="animations fluid top-full menuh-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
					<!-- <![endif]-->
<head>
					<title><?php print $this->translate->_("stumotitle");?></title>

					<!-- Meta -->
					<meta charset="utf-8">
					<meta http-equiv="X-UA-Compatible" content="IE=edge">
					<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">

					<!-- 
	**********************************************************
	In development, use the LESS files and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
	<link rel="stylesheet/less" href="/less/admin/module.admin.page.tables.less" />
					-->
					<!--[if lt IE 9]>
					<link rel="stylesheet" href="/components/library/bootstrap/css/bootstrap.min.css" />
					<![endif]-->
					<link rel="stylesheet" href="/css/admin/module.admin.page.tables.min.css" />
					<link rel="stylesheet" href="/css/admin/menu.css" />

					<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
					<!--[if lt IE 9]>
					<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
					<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
					<![endif]-->

					<script src="/components/library/jquery/jquery.min.js?v=v2.3.0"></script>
					<script src="/components/library/jquery/jquery-migrate.min.js?v=v2.3.0"></script>
					<script src="/components/library/modernizr/modernizr.js?v=v2.3.0"></script>
					<script src="/components/plugins/less-js/less.min.js?v=v2.3.0"></script>
					<script src="/components/modules/admin/charts/flot/assets/lib/excanvas.js?v=v2.3.0"></script>
					<script src="/components/plugins/browser/ie/ie.prototype.polyfill.js?v=v2.3.0"></script>
					<script src="/components/library/jquery-ui/js/jquery-ui.min.js?v=v2.3.0"></script>
					<script src="/components/plugins/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js?v=v2.3.0"></script>
					<script>if (/*@cc_on!@*/false && document.documentMode === 10) { document.documentElement.className+=' ie ie10'; }</script>

</head>

					<!-- Main Container Fluid -->

					<!-- Sidebar menu & content wrapper -->



<body class="document-body">
					<div id="" class="container">
	
						<!-- NAVI  START -->

						<!-- Row -->
						<div class="row innerTB">

							<!-- Col -->
							<div class="col-md-12">

								<!-- Start Featured -->
								<div class="menu">
									<div class="row">
										<div class="col-sm-2">
											<div class="widget">
												<a href="/student/index" class="display-block bg-info innerAll text-center text-white"></i>
											</a>
											<div class="text-center innerAll">
												<a href="/student/index" class="strong  "><?php print $this->translate->_("menua");?></a>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									<div class="col-sm-2">
										<div class="widget">
											<a href="/student/create" class="display-block bg-lightred innerAll text-center text-white"></i>
										</a>
										<div class="text-center innerAll">
											<a href="/student/create" class="strong  "><?php print $this->translate->_("menub");?></a>
											<div class="clearfix"></div>
										</div>
									</div>
								</div>

								<div class="col-sm-2">
									<div class="widget">
										<a href="/session/index" class="display-block bg-purple innerAll text-center text-white"></i>
									</a>
									<div class="text-center innerAll">
										<a href="/session/index" class="strong"><?php print $this->translate->_("menuc");?></a>
										<div class="clearfix"></div>
									</div>
								</div>
							</div>
							<div class="col-sm-2">
								<div class="widget">
									<a href="/session/create" class="display-block bg-gray border-bottom innerAll text-center"></i>
								</a>
								<div class="text-center innerAll">
									<a href="/session/create" class="strong  "><?php print $this->translate->_("menud");?></a>
									<div class="clearfix"></div>

								</div>
							</div>
						</div>
						<div class="col-sm-2">
							<div class="widget">
								<a href="#" class="display-block bg-primary innerAll text-center text-white"></i>
							</a>
							<div class="text-center innerAll">
								<a href="#" class="strong  "><?php print $this->translate->_("menue");?></a>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="widget">
							<a href="#" class="display-block bg-mustard innerAll text-center text-white"></i>
						</a>
						<div class="text-center innerAll">
							<a href="#" class="strong  "><?php print $this->translate->_("menuf");?></a>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- NAVI  end -->
		<h1 class="center">
			<br>
			<?php print $this->translate->_("mjs");?>
			<br>
			<?php print $this->translate->_("stumohead");?>
			<br>
			<br></h1>
		<div class="innerLR">

			<!-- Widget -->
			<div class="widget widget-body-white widget-heading-simple">
				<div class="widget-body">
					<!-- Table -->
					<table class="dynamicTable tableTools table table-striped checkboxs">

						<!-- Table heading -->
						<thead>
							<tr>
								<th class="text-center">
									<div class="checkbox checkbox-single margin-none">
										<label class="checkbox-custom"> <i class="fa fa-fw fa-square-o"></i>
											<input type="checkbox"></label>
									</div>
								</th>
								<th><?php print $this->translate->_("stucol1");?></th>
								<th><?php print $this->translate->_("stucol2");?></th>
								<th><?php print $this->translate->_("stucol3");?>></th>
								<th><?php print $this->translate->_("stucol4");?></th>
								<th><?php print $this->translate->_("stucol5");?></th>
								<th><?php print $this->translate->_("stucol6");?></th>
								<th><?php print $this->translate->_("stucol7");?></th>
								<th><?php print $this->translate->_("stucol8");?></th>
								<th><?php print $this->translate->_("stucol9");?></th>
								<th><?php print $this->translate->_("stucol10");?></th>
								<th><?php print $this->translate->_("stucol11");?></th>
							</tr>
						</thead>
						<!-- // Table heading END -->

						<!-- Table body -->
						<tbody>

						<?php 
							if($this->studentlist){
								//由于国际化问题暂时不用
								//echo $this->partialLoop('partials/row-students.phtml',$this->studentlist);
							}
						?>
						<?php 
							foreach ($this->studentlist as $newrow){
						?>
						<tr class="gradeX">
							<td class="text-center">
								<div class="checkbox checkbox-single margin-none">
									<label class="checkbox-custom"> <i class="fa fa-fw fa-square-o"></i>
										<input type="checkbox"></label>
								</div>
							</td>
							<td><?php echo $newrow->inx;?></td>
							<td><?php echo $newrow->firstName;?></td>
							<td><?php echo $newrow->lastName;?></td>
							<td><?php echo $newrow->phone;?></td>
							<td><?php echo $newrow->email;?></td>
							<td class="center"><?php echo date('Y-m-d',strtotime($newrow->membershipStartDate));?></td>
							<td class="center"><?php echo $newrow->membershipDur;?></td>
							<td class="center"><?php echo $newrow->totalMonthlyMins;?> </td>
							<td class="center"><?php echo $newrow->minsRemaining;?> </td>
							<td class="center">
							<?php 
							$status = '';
							($newrow->acctStatus == '0') ? ($status = $this->translate->_("suspended")) : ($status = $this->translate->_("good"));
							echo $status;
							?>
							</td>
							<td>
								<div class="btn-group btn-group-sm">
									<a href="/student/edit?inx=<?php echo $newrow->inx?>" target="_blank"
										class="btn btn-inverse"> <i class="fa fa-pencil"></i>
									</a>
								</div>
							</td>
						</tr>
						
						<?php
							}	
						?>
						
						</tbody>
						<!-- // Table body END -->

					</table>
					<!-- // Table END -->

				</div>
			</div>

		</div>

	</div>
	<!-- // Content END -->

</div>
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Main Container Fluid END -->

<!-- Global -->
<script>
	var basePath = '',
		commonPath = '/',
		rootPath = '../',
		DEV = false,
		componentsPath = '/components/';
	
	var primaryColor = '#e5412d',
		dangerColor = '#b55151',
		infoColor = '#5cc7dd',
		successColor = '#609450',
		warningColor = '#ab7a4b',
		inverseColor = '#45484d';
	
	var themerPrimaryColor = primaryColor;
	</script>

<script src="/components/library/bootstrap/js/bootstrap.min.js?v=v2.3.0"></script>
<script src="/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v2.3.0"></script>
<script src="/components/plugins/breakpoints/breakpoints.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/datatables/assets/lib/js/jquery.dataTables.min.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/datatables/assets/lib/extras/TableTools/media/js/TableTools.min.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/datatables/assets/lib/extras/ColVis/media/js/ColVis.min.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/datatables/assets/custom/js/DT_bootstrap.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/datatables/assets/custom/js/datatables.init.js?v=v2.3.0"></script>
<script src="/components/modules/admin/forms/elements/fuelux-checkbox/fuelux-checkbox.js?v=v2.3.0"></script>
<script src="/components/modules/admin/forms/elements/bootstrap-select/assets/lib/js/bootstrap-select.js?v=v2.3.0"></script>
<script src="/components/modules/admin/forms/elements/bootstrap-select/assets/custom/js/bootstrap-select.init.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/datatables/assets/lib/extras/FixedHeader/FixedHeader.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/datatables/assets/lib/extras/ColReorder/media/js/ColReorder.min.js?v=v2.3.0"></script>
<script src="/components/modules/admin/tables/classic/assets/js/tables-classic.init.js?v=v2.3.0"></script>
<script src="/components/plugins/jquery.event.move/js/jquery.event.move.js?v=v2.3.0"></script>
<script src="/components/plugins/jquery.event.swipe/js/jquery.event.swipe.js?v=v2.3.0"></script>
<script src="/components/core/js/megamenu.js?v=v2.3.0"></script>
<script src="/components/core/js/core.init.js?v=v2.3.0"></script>
</body>
</html>