<!-- Table row -->
<tr class="gradeX">
	<td class="text-center">
		<div class="checkbox checkbox-single margin-none">
			<label class="checkbox-custom"> <i class="fa fa-fw fa-square-o"></i>
				<input type="checkbox" ></label>
		</div>
	</td>
	<td><?php echo $this->b_inx;?></td>
	<td><?php echo $this->b_firstName." "; echo $this->b_lastName?></td>
	<td><?php echo $this->b_phone;?></td>
	<td><?php echo $this->c_firstName." "; echo $this->c_lastName?></td>
	<td><?php echo $this->c_phone;?></td>
	<td><?php echo $this->d_firstName." "; echo $this->d_lastName?></td>
	<td><?php echo $this->d_phone;?></td>
	<td class="center"><?php echo $this->inx;?></td>
	<td class="center"><?php echo $this->a_scheduleStartTime;?></td>
	
	<?php 
	$d1=strtotime($this->a_actualEndTime);
	$d2=strtotime($this->a_scheduleStartTime);
	$d3=strtotime($this->a_scheduleEndTime);
	$sessionstatus = $this->a_actualEndTime==null?"TBD":"FINISHED";
	$sessionduration = $this->a_actualEndTime==null?($d3-$d2)/60:($d1-$d2)/60;
	
	?>
	<td class="center"><?php echo $sessionduration;?> mins</td>
	<td class="center"><?php echo $sessionstatus ?></td>
	<td>
		<div class="btn-group btn-group-sm">
			<a href="/session/edit?studentinx=<?php echo $this->b_inx;?>&sessioninx=<?php echo $this->inx;?>&instructorinx=<?php echo $this->c_inx;?>&translatorinx=<?php echo $this->d_inx;?>" target="_blank"
				class="btn btn-success"> <i class="fa fa-pencil"></i>
			</a>
		</div>
	</td>
	<td>
		<div class="btn-group btn-group-sm">
			<a href="/session/delete?inx=<?php echo $this->inx?>" class="btn btn-primary"> <i class="fa fa-pencil"></i>
			</a>
		</div>
	</td>
</tr>
<!-- // Table row END -->