<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat"> <![endif]-->
<!--[if gt IE 8]> <html class="animations ie gt-ie8 fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat"> <![endif]-->
<!--[if !IE]><!-->
<html
	class="animations fluid top-full menuh-top sticky-top sidebar sidebar-full sidebar-collapsible sidebar-width-mini sidebar-hat">
<!-- <![endif]-->
<head>
<title></title>

<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">


<!-- 
	**********************************************************
	In development, use the LESS files and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
	<link rel="stylesheet/less" href="less/admin/module.admin.page.login.less" />
	-->

<!--[if lt IE 9]><link rel="stylesheet" href="components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet" href="/css/admin/module.admin.page.login.min.css" />

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->


<script src="/components/library/jquery/jquery.min.js?v=v2.3.0"></script>
<script src="/components/library/jquery/jquery-migrate.min.js?v=v2.3.0"></script>
<script src="/components/library/modernizr/modernizr.js?v=v2.3.0"></script>
<script src="/components/plugins/less-js/less.min.js?v=v2.3.0"></script>
<script
	src="/components/modules/admin/charts/flot/assets/lib/excanvas.js?v=v2.3.0"></script>
<script
	src="/components/plugins/browser/ie/ie.prototype.polyfill.js?v=v2.3.0"></script>
<script>if (/*@cc_on!@*/false && document.documentMode === 10) { document.documentElement.className+=' ie ie10'; }</script>

</head>
<body class="document-body login">

	<!-- Wrapper -->
	<div id="login">

		<div class="container">

			<div class="wrapper">
				<h1>
					<?php print $this->translate->_("mjsportal");?> <em></em>
				</h1>
				<!-- Box -->
				<div class="widget widget-heading-simple widget-body-gray">

					<div class="widget-body">

						<!-- Form -->
						<form method="post" action="/login" class="row" method="post">
							<label><?php print $this->translate->_("usernameoremail");?></label>
							<input name="username" type="text"
								class="input-block-level form-control"
								placeholder="<?php print $this->translate->_("usernameoremail_placeholder");?>" />

							<label><?php print $this->translate->_("password");?></label> <input type="password" name="password"
								class="input-block-level form-control margin-none"
								placeholder="<?php print $this->translate->_("password_placeholder");?>" />
							<div class="separator bottom"></div>

							<div class="col-md-8 padding-none ">
								<div class="uniformjs innerL">
									<label class="checkbox"><input type="checkbox"
										value="remember-me"><?php print $this->translate->_("rememberme");?></label>
								</div>
							</div>
							<div class="col-md-4 pull-right padding-none">
								<button class="btn btn-block btn-inverse" type="submit"><?php print $this->translate->_("signin");?></button>
							</div>

						</form>
						<!-- // Form END -->

					</div>

				</div>
				<!-- // Box END -->
				<div>
				<?php
				if ($this->loginMessage) {
					print $this->loginMessage;
				}
				?>
			</div>
			</div>

		</div>

	</div>
	<!-- // Wrapper END -->





	<!-- Global -->
	<script>
	var basePath = '',
		commonPath = '',
		rootPath = '../',
		DEV = false,
		componentsPath = 'components/';
	
	var primaryColor = '#e5412d',
		dangerColor = '#b55151',
		infoColor = '#5cc7dd',
		successColor = '#609450',
		warningColor = '#ab7a4b',
		inverseColor = '#45484d';
	
	var themerPrimaryColor = primaryColor;
	</script>

	<script
		src="/components/library/bootstrap/js/bootstrap.min.js?v=v2.3.0"></script>
	<script
		src="/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v2.3.0"></script>
	<script src="/components/plugins/breakpoints/breakpoints.js?v=v2.3.0"></script>
	<script
		src="/components/modules/admin/forms/elements/uniform/assets/lib/js/jquery.uniform.min.js?v=v2.3.0"></script>
	<script
		src="/components/modules/admin/forms/elements/uniform/assets/custom/js/uniform.init.js?v=v2.3.0"></script>
	<script
		src="/components/plugins/jquery.event.move/js/jquery.event.move.js?v=v2.3.0"></script>
	<script
		src="/components/plugins/jquery.event.swipe/js/jquery.event.swipe.js?v=v2.3.0"></script>
	<script src="/components/core/js/megamenu.js?v=v2.3.0"></script>
	<script src="/components/core/js/core.init.js?v=v2.3.0"></script>
</body>
</html>