<tr class="gradeX">
	<td class="text-center">
		<div class="checkbox checkbox-single margin-none">
			<label class="checkbox-custom"> <i class="fa fa-fw fa-square-o"></i>
				<input type="checkbox"></label>
		</div>
	</td>
	<td><?php echo $this->inx;?></td>
	<td><?php echo $this->firstName;?></td>
	<td><?php echo $this->lastName;?></td>
	<td><?php echo $this->phone;?></td>
	<td><?php echo $this->email;?></td>
	<td class="center"><?php echo $this->membershipStartDate;?></td>
	<td class="center"><?php echo $this->membershipDur;?></td>
	<td class="center"><?php echo $this->totalMonthlyMins;?> </td>
	<td class="center"><?php echo $this->minsRemaining;?> </td>
	<td class="center">
	<?php 
	$status = '';
	($this->acctStatus == '0') ? ($status = 'SUSPENDED') : ($status = 'GOOD');
	echo $this->acctStatus;
	?>
	</td>
	<td>
		<div class="btn-group btn-group-sm">
			<a href="/student/edit?inx=<?php echo $this->inx?>" target="_blank"
				class="btn btn-inverse"> <i class="fa fa-pencil"></i>
			</a>
		</div>
	</td>
</tr>